### ISSUE TITLE
anchor links don't navigate on mobile blog

### ISSUE THREAD

**Issue by petecarapetyan** [modernweb-dev/rocket#100]
To replicate:

- navigate to blog
- make browser narrower than 1024px to activate media query
- click on the hamburger to expose sidebar
- click on any anchor link

These anchor links fail on my browser anyway. Normal sidebar anchor links on normal sidebar pages work fine, though, as do these same blog links when not in mobile view.

**Comment by daKmoR** [comment]
I don't think this is still applicable in the latest version using `@rocket/engine`? 🤔

I'm closing it - if it still needs fixing feel free to reopen or creating a new issue 🤗
