### ISSUE TITLE
[search] search results position and width change when scrolling

### ISSUE THREAD

**Issue by MathieuPuech** [modernweb-dev/rocket#105]
When you scroll in the results, the search results are moving and when there is no results, the width of the search results in small but not centered.

I made a GIF for illustrating it:

![2021-04-10_01-37-01](https://user-images.githubusercontent.com/9367152/114259650-7e21ed80-999d-11eb-9d92-8fcdb59df4a4.gif)

Bug reproduced on windows chrome Version 89.0.4389.114

**Comment by MathieuPuech** [comment]
instead of having a floating overlay of the search results, the search bar could grow like it is done in [mkdocs-material](https://squidfunk.github.io/mkdocs-material/)

**Comment by daKmoR** [comment]
an update of `@lion/overlays` fixed the positioning.

Growing the search bar sounds nice as well - feel free to open another issue or a pull request for it
