### ISSUE TITLE
missing reference targets

### ISSUE THREAD

**Issue by petecarapetyan** [modernweb-dev/rocket#124]
Created the simplest possible project to demo this. Will provide link in comments 

```
Rocket executes startCommand of RocketStart
Copied 41 files / Wrote 4 files in 1.44 seconds (v0.11.1)
👀 Checking if all internal links work...
🔥 Found a total of 4 files to check!
🔗 Found a total of 114 links to validate!

❌ Found 5 missing reference targets (used by 14 links) while checking 4 files:
  1. missing reference target _site-dev/blog/index.html
    from _site-dev/bar/index.html:191:23 via href="/blog/"
    from _site-dev/bar/yada/index.html:190:23 via href="/blog/"
    from _site-dev/foo/index.html:183:23 via href="/blog/"
    ... 1 more references to this target
  
  2. missing reference target _site-dev/about/slack/index.html
    from _site-dev/bar/index.html:214:23 via href="/about/slack/"
    from _site-dev/bar/yada/index.html:213:23 via href="/about/slack/"
    from _site-dev/foo/index.html:206:23 via href="/about/slack/"
    ... 1 more references to this target
  
  3. missing reference target _site-dev/about/sponsor/index.html
    from _site-dev/bar/index.html:225:23 via href="/about/sponsor/"
    from _site-dev/bar/yada/index.html:224:23 via href="/about/sponsor/"
    from _site-dev/foo/index.html:217:23 via href="/about/sponsor/"
    ... 1 more references to this target
  
  4. missing reference target _site-dev/bar
    from _site-dev/index.html:153:13 via href="/bar"
  
  5. missing reference target _site-dev/bar/yada
    from _site-dev/index.html:154:13 via href="/bar/yada"
  
```

**Comment by petecarapetyan** [comment]
Here is the repo
https://github.com/petecarapetyan/rocketIssue124demo

To replicate:
- clone repo
- npm i
- npm start
- notice 5 messages above in shell
- notice that both of the links on the home page work, even though error messages suggests a problem with same

**Comment by petecarapetyan** [comment]
This is NOT a blocker issue, in that you will still be able to work fine, your sites will deploy fine, etc. For me, it just causes confusion when I read the error message.

**Comment by devnook** [comment]
I've got the same issue when I try to use the tool on https://web.dev (). 
I think the reason for this links triggering an error is the lack of the trailing slash (links to /foo instead of /foo/ ). I'd suggest to fix it by checking the presence of file extension rather than trailing slash, e.g.:  https://github.com/modernweb-dev/rocket/pull/144

**Comment by gdbaldw** [comment]
And, many missing reference targets a template references a page like so,... 

`<a href="/foo">Foo</a>`
