### ISSUE TITLE
Ampersands in Markdown Headers Error with No Information

### ISSUE THREAD

**Issue by petecarapetyan** [modernweb-dev/rocket#131]
If you were to have a  header in a markdown file like so:

`# Fun Errors & Feedback`

It would `npm run start` flawlessly.

But if you ran `npm run build` you would get a very uninformative error such as

```
 Input buffer has corrupt header: glib: XML parse error: Error domain 1 code 68 on line 24 column 28 of data: xmlParseEntityRef: no name

`Error` was thrown:
    Error: Input buffer has corrupt header: glib: XML parse error: Error domain 1 code 68 on line 24 column 28 of data: xmlParseEntityRef: no name
  
```

It would be more helpful if - at minimum - the specific file that contains the ampersand was identified, then a user would at least know where to look for the error. Even better if it said "dude! We can't process an ampersand!"

**Comment by daKmoR** [comment]
I will work on this via https://github.com/modernweb-dev/rocket/issues/236
