### ISSUE TITLE
[check-html-links]mailto: is not skipped

### ISSUE THREAD

**Issue by lvjp** [modernweb-dev/rocket#149]
My static site generator encodes my `mailto:address@example.com` in `&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#97;&#100;&#100;&#114;&#101;&#115;&#115;&#64;&#101;&#120;&#97;&#109;&#112;&#108;&#101;&#46;&#99;&#111;&#109;`

I saw a check in [source code](https://github.com/modernweb-dev/rocket/blob/c5a1d7e8d1f77aa157a5218482c5098a232084e6/packages/check-html-links/src/validateFolder.js#L210) for `^mailto:` links, but it's fail on my link with the error message :
```
  1. missing reference target about/&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#97;&#100;&#100;&#114;&#101;&#115;&#115;&#64;&#101;&#120;&#97;&#109;&#112;&#108;&#101;&#46;&#99;&#111;&#109;
    from about/index.html:698:50 via href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#97;&#100;&#100;&#114;&#101;&#115;&#115;&#64;&#101;&#120;&#97;&#109;&#112;&#108;&#101;&#46;&#99;&#111;&#109;"
```

I think that it's simply a problem of HTML Entities decoding, but I'm not sure.

**Comment by lvjp** [comment]
With the argument `--ignore-link-pattern "mailto:.*"`, the check did no more fail on the link => HTML entities may be well managed :sweat_smile:

**Comment by daKmoR** [comment]
hmmm I think there is some special handling of `;&#` because we are using a byte streaming parser 🤔
