### ISSUE TITLE
Backticks in headings and titles

### ISSUE THREAD

**Issue by bennypowers** [modernweb-dev/rocket#151]
Rocket should handle backticks in document titles

Consider this source:

~~~markdown
# Core >> `@scope/pkg` || 10

This package packs a punch!

## Using `func`

try this!
```js
import { func } from '@scope/pkg';
func();
```
~~~

## Expected
- Document title should be `@scope/pkg`
- Rendered page heading should be `<h1>Core: <code>@scope/pkg</code></h1>`
- Navbar entry should be `<a><code>@scope/pkg</code></a>`
- Navbar child should be `<a href="#func" class="anchor"><code>func</code></a>`

## Actual:
- Document title will be `` `@scope/pkg` ``
- Rendered page heading will be `<h1>Core >> <code>@scope/pkg</code> || 10</h1>`
- Navbar entry will be ``<a>`@scope/pkg`</a>``
- Navbar child should be `<a href="#func" class="anchor"><code></code></a>`

**Comment by daKmoR** [comment]
With the new version of Rocket via `@rocket/engine` this works exactly as expected 👍

feel free to reopen or create a new issue if something is still not working 🤗
