### ISSUE TITLE
_site/assets/webmanifest.json name not replaced on build

### ISSUE THREAD

**Issue by petecarapetyan** [modernweb-dev/rocket#170]
All builds `npm run build` offer an installable called "Rocket" when deployed.

Workaround (except when such as netlify does the build from a git push)  is to `npm run build` and then manually replace the _site/assets/webmanifest.json `name` value with the desired installation name for the service worker

**Comment by daKmoR** [comment]
The solution is to create your own `docs/_assets/webmanifest.json` file - we could add docs for it? care to create a PR?
