### ISSUE TITLE
Title markup should distinguish title from navigation

### ISSUE THREAD

**Issue by sujato** [modernweb-dev/rocket#174]
When Rocket parses the main page title, it takes

```
# First Pages >> Getting Started
```
and produces (simplified):

```
<h1>First Pages: Getting Started</h1>
```
It seems odd to me to add extra text to the page title. Should not the `<h1>` be just the title? “First Pages” is not the title of the page, it’s the step above in the navigation hierarchy. Should not there be a simple option at least to style it? We could do:

```
<h1><span class='supertitle'>First Pages </span>Getting Started</h1>
```

Then we could easily style it or hide it. But it still seems odd semantically. Better:

```
<header>
<span class='supertitle'>First Pages</span>
<h1>Getting Started</h1>
</header>
```

Apart from the defaults, it would also be nice to expose a simple way to modify titles, which doesn’t seem to be the case ATM.

**Comment by daKmoR** [comment]
As we are now using `@rocket/engine` this is supported.

You can write your h1 in any way you want and then define a separate navigation "title".

In markdown it looks like this

~~~md
```js server
export const menuLinkText = 'Hello';
```

# Hello World
~~~

in html it's

```html
<script type="module" server>
export const menuLinkText = 'Hello';
</script>

<h1>Hello World</h1>
```

in js it's this

```js
export const menuLinkText = 'Hello';

export default () => html`
  <h1>Hello World</h1>
`;
```
