### ISSUE TITLE
Can't import existing story to markdown

### ISSUE THREAD

**Issue by yinonov** [modernweb-dev/rocket#176]
rocket [story documentation](https://rocket.modern-web.dev/docs/markdown-javascript/story/) share a working example of hardcoded story

in my use-case I'm trying to import a story to the markdown but failing on an error 

tried many permutation but the error persists
````js
```js script
import { html } from '@mdjs/mdjs-story';
import { Basic } from './stories/button.story.js'
```

```js story
export Basic;
``` 
````
or alternatively
````js
```js story
export const BasicStory = Basic;
``` 
```` 
follow [slack thread](https://lit-and-friends.slack.com/archives/CE6D9DN05/p1624948874228700) for more details

**Comment by bennypowers** [comment]
Try this:

## `./stories/button.story.js`
```js
export const Basic = (args) => html`Ahlan Gever`;
``` 
## `./my-page.md`
~~~markdown
```js story
{% include ./stories/button.story.js %}
```
~~~

You might need to add `./stories/button.story.js` to some ignore lists, e.g. `.eleventyignore`

**Comment by yinonov** [comment]
Thanks @bennypowers that helps.

Still, the stories need to be modified in order to be integrated within rocket markdowns.

Ideally I would expect including existing stories from web components development environment which don't really import smoothly to markdowns

**Comment by bennypowers** [comment]
> Still, the stories need to be modified in order to be integrated within rocket markdowns.

Can you explain what you mean here?

I'm [using the technique](https://github.com/apollo-elements/apollo-elements/blob/next/docs/blog/next-evolution/index.md#try-it-out) pretty successfully for js, css, html, and graphql files, although I'll admit I'm not `include`ing stories

**Comment by daKmoR** [comment]
I just tested it and it works fine for me

👉  `foo.js`
```js
import { html } from '@mdjs/mdjs-preview';

export const foo2 = () => html` here we go `;
```

👉  `preview.md`
````md
# Markdown JavaScript >> Preview ||20

will result in

```js preview-story
import { foo2 } from './foo.js';

export const foo = foo2;
```
````

I will close this for now - if you find a way to reproduce your behavior feel free to reopen or create another issue 🤗

**Comment by yinonov** [comment]
yes ok I understand rocket requires its own couple html function rather than letting lit get involved in the rendering process

**Comment by daKmoR** [comment]
internally it is lit... but this makes sure that the matching lit template gets created for rendering by the preview story web component render function (which is a LitElement)
