### ISSUE TITLE
Navigation can disappear between desktop and mobile zoom levels

### ISSUE THREAD

**Issue by sujato** [modernweb-dev/rocket#177]
There seems to be a problem with the responsive breakpoints. When resizing, at a certain size the desktop navigation disappears, but the mobile does not kick in, so there is no navigation.

Following is on Firefox, with the website approx 1950px wide at 100%.

Zoom to 180%, fine:

![180](https://user-images.githubusercontent.com/6112010/123910629-14264c80-d9be-11eb-9d09-d15e6be30b75.png)

190% — no navigation!

![190](https://user-images.githubusercontent.com/6112010/123910649-1d171e00-d9be-11eb-9198-2f0a42615d8f.png)

200%, mobile nav kicks in.

![200](https://user-images.githubusercontent.com/6112010/123910683-286a4980-d9be-11eb-87a3-49ed58e09dac.png)

It’s a bit tricky to reproduce. It doesn’t seem to occur when simply resizing the window, and I can’t get to happen on Chrome at all.

The same problem occurs for my local vanilla install of rocket.

**Comment by daKmoR** [comment]
With `@rocket/engine` we are now doing SSR of a new drawer component that uses the native dialog element.

I think the described issue will not happen at all with this setup - if it still does feel free to reopen or create a new issue 🤗
