### ISSUE TITLE
Styling suggestion: use a fixed height rather than padding for header

### ISSUE THREAD

**Issue by sujato** [modernweb-dev/rocket#182]
The header height is important for styling, as it pushes the whole page around. 

Currently it uses `padding: 20px 0`  on `#main-header`. But this means that if there are dynamic elements the height can change. 

I see this on https://rocket.modern-web.dev/guides/. If you reload it takes a bit for the search box to appear, and the height shifts meanwhile. It’s more noticeable on FF, where it in fact shifts twice for each page transition.

A better approach might be to get rid of the vertical padding, give a fixed height for the header, and center things with `flex`. The browser can lay out the page without worrying about recalculating the header height.

(Psst, `align-items: center` is currently unused on `#main-header` as it’s not `flex` or `grid`.)

**Comment by daKmoR** [comment]
imho the size should be dynamic as you should decide what gets put in there... but yeah shifting is bad - soo probably best would be to give the search a fixed height.

PS: at some point, we will introduce prerendering with declarative shadow dom which should also solve this problem (but yeah that's probably still a while hence going with the fixed search hight will be good for now)

**Comment by daKmoR** [comment]
now we are using SSR (via @rocket/engine) to output HTML with declarative shadow dom - therefore no more shifting 💪
