### ISSUE TITLE
Replace data base navigation with folder tree navigation

### ISSUE THREAD

**Issue by daKmoR** [modernweb-dev/rocket#201]
I think that will make it way simpler to understand/maintain and create the navigation tree 

![Screenshot 2021-07-06 at 14 14 48](https://user-images.githubusercontent.com/24378/124598193-a5853b00-de64-11eb-88cb-50810011a8bd.png)

https://twitter.com/daKmoR/status/1411678879169880068?s=20

inspiration for implementation
https://github.com/adamduncan/eleventy-auto-navigation

**Comment by bennypowers** [comment]
Maybe we can score #151 along with this issue in the same pr

**Comment by daKmoR** [comment]
file tree navigation is the default since we use @rocket/engine
