### ISSUE TITLE
Problem with sidebar navigation

### ISSUE THREAD

**Issue by vsrohit** [modernweb-dev/rocket#215]
Hi! I am trying to follow the tutorial. I have an issue with sidebar navigation in adding pages (https://rocket.modern-web.dev/guides/first-pages/adding-pages/).

I have created the folder structure and files as mentioned in the tutorial
![image](https://user-images.githubusercontent.com/11407240/125280531-c6510300-e332-11eb-9c3c-8033a1d1d7f9.png)

Contents of files:
index.md:
```
# First pages
```
getting-started.md
````
# First Pages >> Getting Started

This is how you get started.
````
The end result does not show the sidebar navigation for getting started page.

![image](https://user-images.githubusercontent.com/11407240/125280777-1760f700-e333-11eb-8a9a-c45c48ad992d.png)

But, the page is being generated. I could open it using the url.
 
![image](https://user-images.githubusercontent.com/11407240/125280875-3069a800-e333-11eb-9556-0e1739a132e2.png)

**Comment by daKmoR** [comment]
true getting a navigation going was a little trick with this "specific" headline format... it was probably still better then manually linking those files... anyways in the new version of rocket where we use the `@rocket/engine` it now defaults to file based routing so no more special headlines are needed 💪

I am closing this - if there are still questions please open a new issue 🤗
