### ISSUE TITLE
windows error

### ISSUE THREAD

**Issue by MathieuPuech** [modernweb-dev/rocket#24]
When doing `rocket start` on a windows machine, this error is thrown:
```
Error with passthrough copy: (more in DEBUG output)
> Having trouble copying './docs/**/*.{png,gif,jpg,jpeg,svg,css,xml,json,js}'

`TemplatePassthroughManagerCopyError` was thrown
> Error copying passthrough files: Destination is not in the site output directory. Check your passthrough paths.

`TemplatePassthroughError` was thrown
> Destination is not in the site output directory. Check your passthrough paths.

`TemplatePassthroughError` was thrown:
    TemplatePassthroughError: Destination is not in the site output directory. Check your passthrough paths.
        at TemplatePassthrough.copy (C:\Users\mpuech\my-project\node_modules\@11ty\eleventy\src\TemplatePassthrough.js:93:7)
```

Issue seems to come from https://github.com/modernweb-dev/rocket/blob/2a400e09da967684a01e4011d7795685a1494828/packages/cli/src/normalizeConfig.js#L39

Eleventy may not want a windows path.resolve path to work.

If I add in the rocket.config.mjs `outputDevDir: '_site-dev'`, another error is thrown (maybe not related?):

```
rocket start
Problem writing Eleventy templates: (more in DEBUG output)
> Input buffer has corrupt header: glib: XML parse error: Error domain 1 code 64 on line 6 column 56 of data: XML declaration allowed only at the start of the document

`Error` was thrown:
    Error: Input buffer has corrupt header: glib: XML parse error: Error domain 1 code 64 on line 6 column 56 of data: XML declaration allowed only at the start of the document



Copied 37 files / Wrote 0 files in 0.96 seconds (v0.11.1)
(node:36736) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'items' of undefined
    at RocketCli.update (file:///C:/Users/mpuech/my-project/node_modules/@rocket/cli/src/RocketCli.js:176:69)
    at RocketEleventy.write (file:///C:/Users/mpuech/my-project/node_modules/@rocket/cli/src/RocketCli.js:40:28)
    at async RocketEleventy.watch (C:\Users\mpuech\my-project\node_modules\@11ty\eleventy\src\Eleventy.js:650:5)
```

## Steps to reproduce on a windows machine (without WSL)

It's the same steps described in the current getting started page.

```
mkdir my-project
cd my-project
npm init -y
npm install --save-dev @rocket/cli @rocket/launch
```

Add `.gitignore` file with:

```
node_modules/**
/docs/_assets
/docs/_includes
/docs/_data
```

Add `docs/index.md` file with:

```
# Welcome to your Rocket site

Text here, like any markdown file.
```

```
npx rocket start
```

**Comment by MathieuPuech** [comment]
As I was thinking, the second error is not related, it's only because I don't have `docs/_assets/logo.svg`. The error is not very clear.

**Comment by MathieuPuech** [comment]
Another windows issue is the navigation is not generated. It seems to be because path.sep is used (on windows path.sep is `\` which is not the url path separator.

See here: https://github.com/modernweb-dev/rocket/blob/2a400e09da967684a01e4011d7795685a1494828/packages/cli/src/public/rocketEleventyComputed.cjs#L39

**Comment by daKmoR** [comment]
thank you sooo much for looking into that 🙇‍♂️

I addressed your remarks here https://github.com/modernweb-dev/rocket/pull/27

can you try the newest versions 🙏

maybe it works - maybe there are new errors 😅

will need to invest some time to enable windows in the ci

**Comment by MathieuPuech** [comment]
It seems to work, that's perfect, I will reopen an issue if see something
