### ISSUE TITLE
[discussion/question] RocketEleventy.write() - order of function call mergePresets()

### ISSUE THREAD

**Issue by tkgroot** [modernweb-dev/rocket#300]
I was wondering if the order of the function call `await this.__rocketCli.mergePresets();` could be moved below the for-of.

https://github.com/modernweb-dev/rocket/blob/08181194e2c6c6a1f47d867b01f5957ece0b4422/packages/cli/src/RocketCli.js#L38-L43

I'm currently implementing a config where I use the `before11ty()` function to copy files prior, as explained in the [configuration overview lifecycle](https://rocket.modern-web.dev/docs/configuration/overview/#lifecycle) docs.

```javascript
export default {
  async before11ty() {
    await copyDataFiles();
  },
  presets: [rocketLaunch(), rocketSearch()],
}
```

However I realized that copying files into the `/docs/_assets` directory are copied after the `mergePresets()` function has been called, preventing adding static assets. By changing the order that would be resolved. However I do not know if this will create some unwanted side-effects.

**Comment by daKmoR** [comment]
hey there 👋

We are working on the "next" major version of rocket and I think i would make sense to give you a quick tour to see if it might be a better fit if you are just starting something.

Care to have a call? if so can you contact me [Twitter](https://twitter.com/daKmoR) or [slack](https://lit.dev/slack-invite/) (username is daKmoR)

**Comment by daKmoR** [comment]
We are now using our own `@rocket/engine`... so I assume this is no longer an "issue"... if it still is feel free to reopen or create a new issue 🤗
