### ISSUE TITLE
[docs] outdated API of addPlugin/adjustPluginOptions mentioned

### ISSUE THREAD

**Issue by tkgroot** [modernweb-dev/rocket#301]
Multiple places in the documentation reference old addPlugin API, looking at the [release-notes](https://github.com/modernweb-dev/rocket/releases/tag/plugins-manager%400.3.0). Just to name a couple of places I already found, going through the documentation.

https://github.com/modernweb-dev/rocket/blob/08181194e2c6c6a1f47d867b01f5957ece0b4422/docs/docs/configuration/overview.md#L72

https://github.com/modernweb-dev/rocket/blob/08181194e2c6c6a1f47d867b01f5957ece0b4422/docs/docs/eleventy-plugins/mdjs-unified.md#L61

https://github.com/modernweb-dev/rocket/blob/08181194e2c6c6a1f47d867b01f5957ece0b4422/docs/docs/eleventy-plugins/mdjs-unified.md#L36-L40

**Comment by daKmoR** [comment]
I think those have all been fixed or deleted in the meantime - if something is still wrong feel free to reopen or to create a new issue 🤗
