### ISSUE TITLE
[next] issue with Sanity's @portabletext/to-html package

### ISSUE THREAD

**Issue by jaydanurwin** [modernweb-dev/rocket#310]
I'm having issues with the [@portabletext/to-html package](https://github.com/portabletext/to-html). I've used this with 11ty and didn't have any issues but with the latest version of @rocket/engine `^0.1.0-alpha.14` I'm getting this error (see below) as soon as I attempt to pass in the portable text (JSON) from Sanity and try to generate HTML.

```
Named export 'toHTML' not found. The requested module '@portabletext/to-html' is a CommonJS module, which may not support all module.exports as named exports. CommonJS modules can always be imported via the default export, for example using: import pkg from '@portabletext/to-html'; const {toHTML} = pkg;
```

I've looked at the package's docs and under the hood in node_modules and they definitely offer a CJS and ESM version of the package so it seems to me that it's an issue with the way rocket is importing it. I could be wrong though.

## Repro steps

1. clone [this rocket sanity starter repo](https://github.com/jaydanurwin/rocket-sanity-minimal-starter)
2. `npm i`
3. `npm start`
4. navigate to http://localhost:8000/about

Let me know if you need more info!

**Comment by daKmoR** [comment]
The esm export in that package is unfortunately not correct.

I opened an issue for it 

- https://github.com/portabletext/to-html/issues/1

**Comment by jaydanurwin** [comment]
There were able to fix it in the linked issue above, closing this out! 🎉
