### ISSUE TITLE
@rocket/eleventy-plugin-mdjs-unified requires a dependency on @rocket/core

### ISSUE THREAD

**Issue by andrico1234** [modernweb-dev/rocket#329]
After creating a new 11ty project 

```javascript
const pluginMdjs = require("@rocket/eleventy-plugin-mdjs-unified");

module.exports = function (eleventyConfig) {
  eleventyConfig.addPlugin(pluginMdjs);
}
```

I'm getting the following compilation error when I run the standard `npx @11ty/eleventy` script:

```
`Error` was thrown:
[11ty]     Error: Cannot find module '@rocket/core/title'
```

There's no mention in the documentation about dependency on rocket

I'm not sure if this is a problem with the lack of documentation, or with the plugin itself

**Comment by daKmoR** [comment]
jup I can totally image this... will however not be fixed as... as we now have `@rocket/engine` that replaces 11ty as a "renderer".

e.g. this plugin is 11ty plugin is now considered deprecated - if you still wanna use/fix it feel free to open a PR to the legacy branch

https://github.com/modernweb-dev/rocket/tree/legacy
