### ISSUE TITLE
Add information about how link checking is going

### ISSUE THREAD

**Issue by jlengrand** [modernweb-dev/rocket#34]
Just realized I forgot to add an issue for that. 

When testing the tool, I realized I missed some kind of idea of what was gonna happen. 
So I added number of files and links as extra info. 

It could inform the user how much there is to check, as well as whether he is in the right location. 

See feat: #32

**Comment by jlengrand** [comment]
This is how it looks like now : 

![image](https://user-images.githubusercontent.com/921666/105075526-2654a400-5a8a-11eb-9649-ba611a8ac069.png)

**Comment by daKmoR** [comment]
thx again for implementing this 🙇‍♂️
