### ISSUE TITLE
[next] Resolve Build Issues (CSS and Assets)

### ISSUE THREAD

**Issue by jaydanurwin** [modernweb-dev/rocket#352]
## What's not working

- The resolve function for assets is working in dev mode but in production the paths generated for the assets are wrong.
- I noticed the generated CSS file doesn't roll up other CSS files imported using `@import`

## Steps to Reproduce

I open sourced the next version of my personal website that will be built with Rocket (https://github.com/jaydanurwin/jaydanurwin.com-22)

- Clone the repo
- Run the `frontend` in dev mode and notice it's loading everything successfully
- `npm run build` and look at the CSS files and the paths for images are all 404s
- Temporary hosted build available here as well (https://jaydanurwin-rocket.netlify.app/)

**Comment by jaydanurwin** [comment]
Sounds like this was a known issue for @imports not working in resolves files. @daKmoR let me know if you would like me to close this or not if you already have another issue open for bundling CSS files using @import.

**Comment by daKmoR** [comment]
tracking issue is here https://github.com/modernweb-dev/rocket/issues/287
