### ISSUE TITLE
the link in readme.md was 404

### ISSUE THREAD

**Issue by zxhycxq** [modernweb-dev/rocket#427]
The link was 404.
`https://github.com/modernweb-dev/rocket/tree/main/packages/check-html-links`

![image](https://user-images.githubusercontent.com/11674203/186107898-06d8f827-f0a4-4a2b-a673-5767f1bfa002.png)

may be it is `https://rocket.modern-web.dev/tools/check-html-links/overview/`

**Comment by daKmoR** [comment]
thank you for reporting 🙇‍♂️

I updated the link to what you suggested 🤗
