### ISSUE TITLE
check-html-links add an option to ignore certain folders/references 

### ISSUE THREAD

**Issue by Mogztter** [modernweb-dev/rocket#51]
As mentioned on Twitter, some URLs might not be resolvable "statically". For instance, some URLs might be served by Netlify proxy or by another subsystem.

To accommodate this use case, we should provide an option to ignore certain folders/references.

In addition, we could pass a "filter function" to the `resolveLinks` function to decide if we should process or ignore a given link. That might be useful, when `check-html-links` will be able to check external links as some users will probably want to disable this feature. Using a filter function this will be straightforward:

```js
import {validateFolder} from 'check-html-links'


validateFolder('_site', { 
  options: {
    // ignore external url
    ignoreLink: (hrefObj) => value.startsWith('//') || value.startsWith('http')
  }
})
```

We could also introduce a "resolver function" if we want to emulate a proxy (i.e., when files exist on the local file system but on another path). But that's probably out-of-scope for now.

And now the tough question, how should we name this option :sweat_smile:

```
$ npx check-html-links _site --ignore="/speedlify/**,**debug**,{app,docs,tests}/**/*.html"
```

We might need to add `link` or `url` to make it clear (otherwise, one might think that it will ignore files).
We could also add `pattern` if we want to support glob expressions:

- `--ignore`
- `--ignore-pattern`
- `--ignore-link-pattern`
- `--ignore-link-patterns`
- `--skip`

I think that `patterns` should be plural if we can define multiple patterns using a comma-separated list or singular if we can use the option multiple times:

```
$ npx check-html-links _site \
  --ignore-link-pattern="/speedlify/**" \
  --ignore-link-pattern="**debug**" \
  --ignore-link-pattern="{app,docs,tests}/**/*.html"
```

And last question, should we add https://www.npmjs.com/package/yargs-parser to parse `process.argv`? For reference, https://github.com/yargs/yargs has 7 dependencies so not great.
I'm not familiar with https://www.npmjs.com/package/commander but it has 0 dependency... so it might be a potential solution.

**Comment by jlengrand** [comment]
Really like that, thanks for the thorough preleminary work @Mogztter ! I have had the same (but simpler) use case last week when trying to run a website with a javadoc folder. Creates huge amounts of links that will be valid by definition. 

I 'll look deeper into this!

**Comment by daKmoR** [comment]
we probably need 2 separate flags 🤔

e.g. on pattern to not check links for files that do get checked... and one pattern to not even analyze/check for

```
$ npx check-html-links _site \
  --ignore-link-pattern="/speedify/*" \
  --skip-checking-pattern="./folder-to-ignore/*"
```

for a lib to parse process.argv... it will probably be `command-line-args` as it's also used in all the other repos we have... it's probably not perfect with a deps tree of 5... but it's at least knowledge we can reuse across multiple projects


PS: the node API is probably going to change 😅

**Comment by jlengrand** [comment]
`command-line-args` seems like a deal. 

Right, I indeed see now that we have two use cases indeed. Interesting. The skip seems rather easy to implement, but I wonder if the skip will not increase the processing complexity? Will have a look at the current implementation

**Comment by Mogztter** [comment]
Thanks for your replies!

Should I go forward and implement `--ignore-link-pattern` using `command-line-args`?
Any thoughts on the Node API? Should we introduce an "options object" as a second argument of the `validateFolder` function?

**Comment by jlengrand** [comment]
Go for it. I started looking at it yesterday but didn't get on the actual implementation yet.

**Comment by daKmoR** [comment]
thanks again for implementing 🙇‍♂️
