### ISSUE TITLE
Post titles containing character entities appear in plain text in the tab bar

### ISSUE THREAD

**Issue by bennypowers** [modernweb-dev/rocket#64]
Consider a user wanting to put an element name in a post title

```md
# Components >> &lt;some-button&gt;
```

This should render fine in the navigation sidebar, in the post's `h1`, etc.

However, the `document.title`, shown in the tab bar, shows the literal `&lt;` (and-el-tee-semicolon) instead of the decoded `<`

<img width="675" alt="Screen Shot 2021-02-04 at 0 28 47" src="https://user-images.githubusercontent.com/1466420/106867656-89734700-66d6-11eb-8fce-e1328d4c61eb.png">

This is likely to be an issue for web component authors

**Comment by daKmoR** [comment]
will work on it via https://github.com/modernweb-dev/rocket/issues/236
