### ISSUE TITLE
Getting started process fails with 'layout does not exist'

### ISSUE THREAD

**Issue by petecarapetyan** [modernweb-dev/rocket#65]
This is a new one just today.

I run the standard getting started process daily and it always works - as from `https://rocket.modern-web.dev/guides/first-pages/getting-started/`, from mkdir to ... to `npm install --save-dev @rocket/cli @rocket/launch` and then through the rest of the guide.

Changes introduced in last 24 hours now produce this error:
`Error: You’re trying to use a layout that does not exist: home.njk`

**Comment by petecarapetyan** [comment]
Repeated again today:

- go to rocket getting started guide
- repeat exact specified steps starting with `mkdir ...`
- same exact error

**Comment by daKmoR** [comment]
I did run it right now and it works fine 😅

do you maybe have an outdated rocket or launch in your node_modules? maybe global node_modules? 🤔

maybe check your versions that got installed?

```
~/html/my-project$ npm list @rocket/launch
my-project@1.0.0 /Users/ff67qn/html/my-project
└── @rocket/launch@0.4.0

~/html/my-project$ npm list @rocket/cli
my-project@1.0.0 /Users/ff67qn/html/my-project
└── @rocket/cli@0.5.2
```

**Comment by petecarapetyan** [comment]
I was using a previous set of markdown files

This is what killed me - the layout: home.njk part

```---
title: Fins
layout: home.njk
---```

apologize for the noise
