### ISSUE TITLE
Mobile trigger hard-coded to 1024px

### ISSUE THREAD

**Issue by petecarapetyan** [modernweb-dev/rocket#73]
Because RocketDrawer.js seems to be hard-coded to 1024px per this line:

`this.useOverlayMediaQuery = '(max-width: 1024px)';`

then my understanding is that I am forced to make all my `@media` queries for mobile break on the same value, else I get weird results?

It would be more ideal if RocketDrawer were configurable such that `<rocket-drawer something="700">` were  possible, giving me the ability to set my mobile trigger media queries on a different value for different themes.

**Comment by Matsuuu** [comment]
This has been addressed on the commit [here](https://github.com/modernweb-dev/rocket/commit/c87caaed2d225f88b27a542e69f57dcd596f367b) , and will likely be deployed in the next Rocket version (if not already :) )

**Comment by daKmoR** [comment]
it's released now 👍
