### ISSUE TITLE
The "show code" button in the mdjs viewer is overlapping our content

### ISSUE THREAD

**Issue by gerjanvangeest** [modernweb-dev/rocket#86]
Can the mdjs viewer have more padding in the bottom, so the "show code" doesn't overlap our code examples?

this is what currently happens:

![image](https://user-images.githubusercontent.com/10164421/111271531-99fdd200-8631-11eb-9088-3571263a04b9.png)

And with for instance `padding-bottom: 40px`:

![image](https://user-images.githubusercontent.com/10164421/111272226-97e84300-8632-11eb-8b19-283a67e72dbd.png)

**Comment by daKmoR** [comment]
the viewer has been completely restructured and it's now an accordion underneath the example. 
No more overlaps 👍
