### ISSUE TITLE
The "missing reference targets" check should exclude telephone numbers, e.g. "tel:99999"

### ISSUE THREAD

**Issue by gdbaldw** [modernweb-dev/rocket#88]
❌ Found 1 missing reference targets (used by 2 links) while checking 21 files:
  1. missing reference target _site-dev/contact-us/tel:99999
    from _site-dev/contact-us/index.html:151:17 via href="tel:99999"
    from _site-dev/contact-us/index.html:157:14 via href="tel:99999"

**Comment by daKmoR** [comment]
jup totally right - that should be ignored 🙈
