### ISSUE TITLE
List files in parent of _includes, and its subdirectories

### ISSUE THREAD

**Issue by gdbaldw** [modernweb-dev/rocket#89]
Rocket has the very useful feature of listing files within an _includes subdirectory:

{% for blockName, blockPath in _joiningBlocks._layoutHome.content %}

Could this feature be extended to assets within docs subdirectories? Specifically, looping through a directory of images to instantiate a layout?

**Comment by daKmoR** [comment]
I don't think this is still applicable in the latest version using `@rocket/engine`? 🤔

I'm closing it - if it still needs fixing feel free to reopen or creating a new issue 🤗
